<?php
// modules/export/docx.php — GG-029: Export Lesson Plan as DOCX
require_once '../../config/session.php';
require_once '../../config/db.php';
require_once '../../config/gemini.php'; // FIX (June 2026): kailangan para sa getSectionLabels()
requireLogin();
$tid = $_SESSION['teacher_id'];
$id  = (int)($_GET['id'] ?? 0);

$lp = mysqli_fetch_assoc(mysqli_query($conn, "SELECT * FROM lesson_plans WHERE id='$id' AND teacher_id='$tid'"));

// FIX: Inilipat ang existence check bago ang UPDATE export_count
// (dating tumatakbo ang UPDATE kahit walang nahanap na record).
if (!$lp) {
    header("Location: ../library/index.php");
    exit();
}

// FIX: Backend-level na proteksyon (hindi lang UI) laban sa pag-
// export ng lesson plan na hindi pa na-save sa Library. Defense-in-
// depth — kasalo ang parehong check sa pdf.php.
if ((int)($lp['is_saved'] ?? 0) !== 1) {
    header("Location: ../generator/index.php?export_error=not_saved");
    exit();
}

// Track export count — pagkatapos lang ng existence + is_saved check
mysqli_query($conn, "UPDATE lesson_plans SET export_count = export_count + 1 WHERE id='$id'");

$title    = $lp['title'];
$grade    = $lp['grade_level'];
$subject  = $lp['subject'];
$topic    = $lp['topic'] ?? '';
$duration = $lp['duration'] ?? '45 minutes';
$strategy = $lp['strategy'] ?? 'Discussion-Based';
$date     = date('F d, Y', strtotime($lp['updated_at']));
$teacher  = $_SESSION['teacher_name'];
$filename = preg_replace('/[^a-z0-9]+/i', '_', $title) . '.docx';

// FIX (June 2026): dati, hardcoded generic labels ang ginamit dito
// ("I. Learning Objectives", atbp.) kaya kahit ILAW o 4A's na lesson
// plan ang i-export, lumalabas pa rin ang generic DLP-style labels.
// AYOS: kunin ang format na talagang ginamit (mula sa 'format' column)
// tapos gamitin ang getSectionLabels() mula sa config/gemini.php —
// parehong function na ginagamit ng Generator page, kaya tugma na.
$format = $lp['format'] ?? 'DLP';
$curriculum = $lp['curriculum'] ?? 'MATATAG';
$sections = [];
foreach (getSectionLabels($format) as $key => [$ico, $label, $desc]) {
    $sections[$key] = $label;
}

// Build DOCX using raw XML
function escXml($str) {
    return htmlspecialchars($str, ENT_XML1, 'UTF-8');
}

function makeParas($text) {
    $lines = explode("\n", $text);
    $xml = '';
    foreach ($lines as $line) {
        $line = trim($line);
        $xml .= '<w:p><w:r><w:t xml:space="preserve">' . escXml($line ?: ' ') . '</w:t></w:r></w:p>';
    }
    return $xml;
}

$body = '';

// Title
$body .= '<w:p><w:pPr><w:jc w:val="center"/></w:pPr>
  <w:r><w:rPr><w:b/><w:sz w:val="32"/><w:color w:val="1C3557"/></w:rPr>
  <w:t>🎓 Gurong GabAI — Lesson Plan</w:t></w:r></w:p>';

// Subtitle
$body .= '<w:p><w:pPr><w:jc w:val="center"/></w:pPr>
  <w:r><w:rPr><w:sz w:val="20"/><w:color w:val="64748B"/></w:rPr>
  <w:t>AI-Powered Lesson Plan Generator | DepEd Matatag Curriculum</w:t></w:r></w:p>';

$body .= '<w:p></w:p>';

// Meta info
$metaItems = [
    'Teacher' => $teacher,
    'Grade Level' => $grade,
    'Subject' => $subject,
    'Topic' => $topic,
    'Duration' => $duration,
    'Teaching Strategy' => $strategy,
    'Date' => $date,
    'Curriculum' => $curriculum,
    'Format' => $format,
];
foreach ($metaItems as $label => $val) {
    $body .= '<w:p>
      <w:r><w:rPr><w:b/><w:color w:val="1C3557"/></w:rPr><w:t xml:space="preserve">' . escXml($label) . ': </w:t></w:r>
      <w:r><w:t>' . escXml($val) . '</w:t></w:r>
    </w:p>';
}

$body .= '<w:p></w:p>';

// Disclaimer
$body .= '<w:p><w:r><w:rPr><w:i/><w:color w:val="92400E"/></w:rPr>
  <w:t>⚠️ AI-generated content is for reference only. Always review before using in the classroom.</w:t>
</w:r></w:p><w:p></w:p>';

// Sections
foreach ($sections as $key => $label) {
    // Section heading
    $body .= '<w:p>
      <w:r><w:rPr><w:b/><w:sz w:val="24"/><w:color w:val="FFFFFF"/>
        <w:shd w:val="clear" w:color="auto" w:fill="1C3557"/>
      </w:rPr><w:t>' . escXml($label) . '</w:t></w:r>
    </w:p>';
    // Section content
    $body .= makeParas($lp[$key] ?? '');
    $body .= '<w:p></w:p>';
}

// Footer
$body .= '<w:p><w:pPr><w:jc w:val="center"/></w:pPr>
  <w:r><w:rPr><w:sz w:val="18"/><w:color w:val="94A3B8"/></w:rPr>
  <w:t>Generated by Gurong GabAI | AI-generated content is for reference only.</w:t></w:r>
</w:p>';

// Full DOCX XML
$docXml = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:wpc="http://schemas.microsoft.com/office/word/2010/wordprocessingCanvas"
  xmlns:mo="http://schemas.microsoft.com/office/mac/office/2008/main"
  xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
  xmlns:mv="urn:schemas-microsoft-com:mac:vml"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"
  xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math"
  xmlns:v="urn:schemas-microsoft-com:vml"
  xmlns:wp14="http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing"
  xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing"
  xmlns:w10="urn:schemas-microsoft-com:office:word"
  xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"
  xmlns:w14="http://schemas.microsoft.com/office/word/2010/wordml"
  xmlns:wpg="http://schemas.microsoft.com/office/word/2010/wordprocessingGroup"
  xmlns:wpi="http://schemas.microsoft.com/office/word/2010/wordprocessingInk"
  xmlns:wne="http://schemas.microsoft.com/office/word/2006/wordml"
  xmlns:wps="http://schemas.microsoft.com/office/word/2010/wordprocessingShape"
  mc:Ignorable="w14 wp14">
  <w:body>' . $body . '
    <w:sectPr>
      <w:pgSz w:w="12240" w:h="15840"/>
      <w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440"/>
    </w:sectPr>
  </w:body>
</w:document>';

// Relationships
$relsXml = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
</Relationships>';

$wordRelsXml = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>
</Relationships>';

$contentTypesXml = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
  <Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/>
</Types>';

$stylesXml = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:docDefaults>
    <w:rPrDefault><w:rPr>
      <w:rFonts w:ascii="Arial" w:hAnsi="Arial"/>
      <w:sz w:val="22"/>
    </w:rPr></w:rPrDefault>
  </w:docDefaults>
</w:styles>';

// Build ZIP (DOCX)
$tmpDir = sys_get_temp_dir() . '/gurong_docx_' . uniqid();
mkdir($tmpDir);
mkdir($tmpDir . '/_rels');
mkdir($tmpDir . '/word');
mkdir($tmpDir . '/word/_rels');

file_put_contents($tmpDir . '/[Content_Types].xml', $contentTypesXml);
file_put_contents($tmpDir . '/_rels/.rels', $relsXml);
file_put_contents($tmpDir . '/word/document.xml', $docXml);
file_put_contents($tmpDir . '/word/_rels/document.xml.rels', $wordRelsXml);
file_put_contents($tmpDir . '/word/styles.xml', $stylesXml);

// Create zip
$zipFile = sys_get_temp_dir() . '/' . $filename;
$zip = new ZipArchive();
$zip->open($zipFile, ZipArchive::CREATE | ZipArchive::OVERWRITE);
$zip->addFile($tmpDir . '/[Content_Types].xml', '[Content_Types].xml');
$zip->addFile($tmpDir . '/_rels/.rels', '_rels/.rels');
$zip->addFile($tmpDir . '/word/document.xml', 'word/document.xml');
$zip->addFile($tmpDir . '/word/_rels/document.xml.rels', 'word/_rels/document.xml.rels');
$zip->addFile($tmpDir . '/word/styles.xml', 'word/styles.xml');
$zip->close();

// Download
header('Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document');
header('Content-Disposition: attachment; filename="' . $filename . '"');
header('Content-Length: ' . filesize($zipFile));
readfile($zipFile);

// Cleanup
unlink($zipFile);
array_map('unlink', glob($tmpDir . '/_rels/*'));
array_map('unlink', glob($tmpDir . '/word/_rels/*'));
array_map('unlink', glob($tmpDir . '/word/*'));
array_map('unlink', glob($tmpDir . '/*'));
rmdir($tmpDir . '/_rels');
rmdir($tmpDir . '/word/_rels');
rmdir($tmpDir . '/word');
rmdir($tmpDir);
exit();
?>